use [11703990404_µËÇÅ];
CREATE TABLE S(
SNO CHAR(2) PRIMARY KEY,
SNAME CHAR(20) UNIQUE,
STATUS SMALLINT,
CITY CHAR(20));
SELECT *FROM S;
CREATE TABLE P(
PNO CHAR(2) PRIMARY KEY,
PNAME CHAR(20) UNIQUE,
COLOR CHAR(10),
WEIGHT SMALLINT);
SELECT *FROM P;
CREATE TABLE J(
JNO CHAR(2) PRIMARY KEY,
JNAME CHAR(20) UNIQUE,
CITY CHAR(20));
SELECT *FROM J;
CREATE TABLE SPJ(
SNO CHAR(2),
PNO CHAR(2),
JNO CHAR(2),
QTY SMALLINT,
PRIMARY KEY (SNO,PNO,JNO),
FOREIGN KEY(SNO) REFERENCES S(SNO),
FOREIGN KEY (PNO) REFERENCES P(PNO),
FOREIGN KEY (JNO) REFERENCES J(JNO)
);
SELECT *FROM SPJ;