--5.
--(1)
SELECT SNAME,CITY FROM S;
--(2)
SELECT PNAME,COLOR,WEIGHT FROM P;
--(3)
SELECT JNO FROM SPJ
WHERE SNO='S1';
--(4)
SELECT PNAME,QTY FROM SPJ,P
WHERE JNO='J2' AND P.PNO=SPJ.PNO;
--(5)
SELECT P.PNO FROM SPJ,P,S
WHERE SPJ.PNO=P.PNO AND SPJ.SNO=S.SNO AND S.CITY='上海';
--(6)
SELECT J.JNAME FROM SPJ,J,S
WHERE SPJ.JNO=J.JNO AND SPJ.SNO=S.SNO AND S.CITY='上海';
--(7)
select * from s;
select * from p;
select * from j;
select * from spj;
--fist
SELECT JNO FROM J
EXCEPT( 
		SELECT JNO
		FROM SPJ,S,P
		WHERE SPJ.SNO=S.SNO AND SPJ.PNO=P.PNO  AND S.CITY='天津' AND color='红');
--second
SELECT JNO
FROM J
WHERE NOT EXISTS(
		SELECT * FROM SPJ,S,P
		WHERE SPJ.JNO=J.JNO AND SPJ.SNO=S.SNO AND SPJ.PNO=P.PNO AND S.CITY='天津' AND color='红');
