CREATE VIEW S_P_Q_sanjian(SNO,PNO,QTY) AS
SELECT S.SNO,P.PNO,SPJ.QTY 
FROM S,P,J,SPJ
WHERE S.SNO=SPJ.SNO AND P.PNO=SPJ.PNO AND J.JNO=SPJ.JNO AND JNAME='Èý½¨';
SELECT * FROM S_P_Q_sanjian;
--9.(1)
SELECT PNO,SUM(QTY) pno_num FROM S_P_Q_sanjian
GROUP BY PNO;
--9.(2)
SELECT * FROM S_P_Q_sanjian
WHERE SNO='S1';