USE [11703990404_µËÇÅ];
CREATE TABLE SAG(
Sno CHAR(9),
AG SMALLINT,
PRIMARY KEY (Sno),
FOREIGN KEY(Sno) REFERENCES Student(Sno)
);
INSERT
INTO SAG(Sno,AG)
SELECT Sno,AVG(Grade)
FROM SC
GROUP BY Sno;
SELECT * FROM SAG;